osx_image: xcode7.3

language: node_js

os:
  - osx

cache:
  directories:
    - node_modules

deploy:
  skip_cleanup: true
  provider: script
  script: npm version patch && git push --tags && npm run release
  on:
    branch: single-package-json
