osx_image: xcode7.3

language: node_js

os:
  - osx

cache:
  directories:
    - node_modules

deploy:
  skip_cleanup: true
  provider: script
  script: bash housekeeping/deploy.sh
  on:
    branch: master
